import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { construirDist, MODULOS_ISOMORFOS } from "../src/build.mjs";
import { raizConCuentas } from "./ayuda/cuentas.mjs";

test("construirDist copia imágenes, panel, módulos isomorfos e índice", () => {
  const raiz = raizConCuentas({ cuentas: ["sinlinea", "prueba"], prefijo: "dist-" });
  fs.writeFileSync(path.join(raiz, "public/img/a.jpg"), "jpg");
  fs.writeFileSync(path.join(raiz, "public/img/.gitkeep"), "");
  fs.mkdirSync(path.join(raiz, "public/ilus"), { recursive: true });
  fs.writeFileSync(path.join(raiz, "public/ilus/x.jpg"), "jpg");
  fs.mkdirSync(path.join(raiz, "panel"), { recursive: true });
  fs.writeFileSync(path.join(raiz, "panel/index.html"), "<p>panel</p>");
  fs.mkdirSync(path.join(raiz, "src/lib"), { recursive: true });
  for (const f of MODULOS_ISOMORFOS) fs.copyFileSync(`src/lib/${f}`, path.join(raiz, "src/lib", f));
  const dist = construirDist({ raiz });
  assert.ok(fs.existsSync(path.join(dist, "img/a.jpg")));
  assert.ok(!fs.existsSync(path.join(dist, "img/.gitkeep")));
  assert.ok(!fs.existsSync(path.join(dist, "ilus")), "public/ilus no debe publicarse en dist/ (I2)");
  assert.ok(fs.existsSync(path.join(dist, "panel/index.html")));
  assert.ok(fs.existsSync(path.join(dist, "panel/lib/estados.mjs")));
  assert.ok(fs.existsSync(path.join(dist, "panel/lib/texto.mjs")), "el panel necesita texto.mjs para validar titular y bajada");
  assert.ok(fs.existsSync(path.join(dist, ".nojekyll")));
  assert.match(fs.readFileSync(path.join(dist, "index.html"), "utf8"), /url=panel\//);
  const cfgPanel = JSON.parse(fs.readFileSync(path.join(dist, "panel/config.json")));
  assert.equal(cfgPanel.franjas.length, 6, "franjas de la cuenta principal (compatibilidad)");
  assert.equal(cfgPanel.zonaHoraria, "America/Panama");
  assert.deepEqual(cfgPanel.cuentas.map((c) => c.id), ["sinlinea", "prueba"], "(M1) lista de cuentas para el selector");
  assert.equal(cfgPanel.cuentas[1].nombre, "Cuenta de prueba");
  assert.equal(cfgPanel.cuentas[1].franjas.length, 3);
  assert.equal(cfgPanel.cuentas[1].marca.usuario, "@prueba.diario");
  assert.equal(JSON.stringify(cfgPanel).includes("Secreto"), false, "el panel nunca recibe nombres de secretos ni claves");
});
